import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-plannin',
  templateUrl: './plannin.component.html',
  styleUrls: ['./plannin.component.css']
})
export class PlanninComponent implements OnInit {

  public loop = [
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
    {name: 'loo'},
  ]

  constructor() {}

  ngOnInit(): void {
  }

}
